
# This is an input file necessary for running the workbook

system_message: You are an expert in understanding Retail SKUs. You have an understanding across different industries and able to create Consumer Decision Trees.  # Necessary
super_class: Bread  # (Optional) name of the type of dataset  i.e snacks, furniture, 
level1_task: preperation, type, brand name
# level2_task: category
# level3_task: sub category
# level4_task: flavour
# level5_task: sub_category
# level2_options: Nuts,Potato Chips,Local Snacks,Cracker,Others
# use_rational: True
# level1_example: False
# level3_sequence: level2
level1_input: SKU
# level2_input: SKU
# level3_input: SKU,level2_task
# level4_input: SKU
# level5_input: SKU,level1_task



