system_content_part1 : You are a Retail expert with expertise in undertanding SKUs for 
super_category : snacks 
number_of_levels : 5
level1 : Category of snack
level2 : Brand Name or Company name
level3 : Pack size
level4 : Flavour
level5 : Type

